# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - run: yarn
      - run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - name: Create .env
        run: |
          touch .env
          echo ENV=${{ env.ENV }} >> .env
          echo EXPRESS_HOST=${{ env.EXPRESS_HOST }} >> .env
          echo EXPRESS_PORT=${{ env.EXPRESS_PORT }} >> .env
          echo MONGO_URI=${{ env.MONGO_URI }} >> .env
          echo KAFKA_CONSUMER_GROUP=${{ env.KAFKA_CONSUMER_GROUP }} >> .env
          echo JWT_SECRET=${{ env.JWT_SECRET }} >> .env
          echo JWT_ISSUER=${{ env.JWT_ISSUER }} >> .env
      - run: yarn
      - run: yarn test

  publish-gpr:
    name: Publish to NPM
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org
          # Defaults to the user or organization that owns the workflow file
          scope: "@codrjs"
      - run: yarn
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/
      - run: cd dist && yarn publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
